# Generated by Django 2.0.6 on 2018-06-14 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessControl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'AccessControl',
                'permissions': (('cyeap_tomcat_look', 'Tomcat部署管理'),),
            },
        ),
    ]
