# Generated by Django 2.0.3 on 2018-06-22 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TomcatServer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='TomcatID')),
                ('name', models.CharField(max_length=128, verbose_name='Tomcat目录名称')),
                ('alias', models.CharField(blank=True, max_length=128, null=True, verbose_name='Tomcat别名')),
                ('version', models.CharField(blank=True, max_length=128, null=True, verbose_name='Tomcat版本')),
                ('deploy_path', models.CharField(default='/local/server/', max_length=128, verbose_name='部署路径')),
                ('ip4_inner', models.CharField(blank=True, max_length=32, null=True, verbose_name='内网IP_v4')),
                ('ip4_outer', models.CharField(blank=True, max_length=32, null=True, verbose_name='外网IP_v4')),
                ('http_port', models.SmallIntegerField(verbose_name='HTTP端口')),
                ('shutdown_port', models.SmallIntegerField(verbose_name='SHUTDOWN端口')),
                ('ajp_port', models.SmallIntegerField(verbose_name='AJP端口')),
                ('is_run', models.BooleanField(verbose_name='运行状态')),
                ('config', models.TextField(blank=True, null=True, verbose_name='配置文件')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now_add=True, verbose_name='更新时间')),
                ('remark', models.CharField(blank=True, max_length=512, null=True, verbose_name='备注')),
            ],
            options={
                'db_table': 'tomcat_server',
            },
        ),
        migrations.CreateModel(
            name='TomcatWebapp',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='项目编号')),
                ('name', models.CharField(max_length=128, verbose_name='项目名称')),
                ('alias', models.CharField(blank=True, max_length=128, null=True, verbose_name='项目别名')),
                ('deploy_path', models.CharField(default='/local/webapp/', max_length=128, verbose_name='部署路径')),
                ('source_path', models.CharField(max_length=128, verbose_name='SVN源路径')),
                ('current_version', models.CharField(blank=True, max_length=128, null=True, verbose_name='项目版本')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now_add=True, verbose_name='更新时间')),
                ('remark', models.CharField(blank=True, max_length=512, null=True, verbose_name='备注')),
            ],
            options={
                'db_table': 'tomcat_webapp',
            },
        ),
        migrations.AddField(
            model_name='tomcatserver',
            name='webapp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cyeap_tomcat.TomcatWebapp', verbose_name='部署应用'),
        ),
    ]
