# Generated by Django 2.0.6 on 2018-06-14 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cyeap_tomcat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tomcatserver',
            name='ajp_port',
            field=models.SmallIntegerField(verbose_name='AJP端口'),
        ),
        migrations.AlterField(
            model_name='tomcatserver',
            name='alias',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Tomcat别名'),
        ),
        migrations.AlterField(
            model_name='tomcatserver',
            name='config',
            field=models.TextField(blank=True, null=True, verbose_name='配置文件'),
        ),
        migrations.AlterField(
            model_name='tomcatserver',
            name='create_time',
            field=models.DateTimeField(auto_now=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='tomcatserver',
            name='deploy_path',
            field=models.CharField(default='/local/server/', max_length=128, verbose_name='部署路径'),
        ),
        migrations.AlterField(
            model_name='tomcatserver',
            name='http_port',
            field=models.SmallIntegerField(verbose_name='HTTP端口'),
        ),
        migrations.AlterField(
            model_name='tomcatserver',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='TomcatID'),
        ),
        migrations.AlterField(
            model_name='tomcatserver',
            name='ip4_inner',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='内网IP_v4'),
        ),
        migrations.AlterField(
            model_name='tomcatserver',
            name='ip4_outer',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='外网IP_v4'),
        ),
        migrations.AlterField(
            model_name='tomcatserver',
            name='is_run',
            field=models.BooleanField(verbose_name='运行状态'),
        ),
        migrations.AlterField(
            model_name='tomcatserver',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Tomcat目录名称'),
        ),
        migrations.AlterField(
            model_name='tomcatserver',
            name='remark',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='tomcatserver',
            name='shutdown_port',
            field=models.SmallIntegerField(verbose_name='SHUTDOWN端口'),
        ),
        migrations.AlterField(
            model_name='tomcatserver',
            name='update_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='tomcatserver',
            name='version',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Tomcat版本'),
        ),
        migrations.AlterField(
            model_name='tomcatserver',
            name='webapp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cyeap_tomcat.TomcatWebapp', verbose_name='部署应用'),
        ),
        migrations.AlterField(
            model_name='tomcatwebapp',
            name='alias',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='项目别名'),
        ),
        migrations.AlterField(
            model_name='tomcatwebapp',
            name='create_time',
            field=models.DateTimeField(auto_now=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='tomcatwebapp',
            name='current_version',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='项目版本'),
        ),
        migrations.AlterField(
            model_name='tomcatwebapp',
            name='deploy_path',
            field=models.CharField(default='/local/webapp/', max_length=128, verbose_name='部署路径'),
        ),
        migrations.AlterField(
            model_name='tomcatwebapp',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='项目编号'),
        ),
        migrations.AlterField(
            model_name='tomcatwebapp',
            name='name',
            field=models.CharField(max_length=128, verbose_name='项目名称'),
        ),
        migrations.AlterField(
            model_name='tomcatwebapp',
            name='remark',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='tomcatwebapp',
            name='source_path',
            field=models.CharField(max_length=128, verbose_name='SVN源路径'),
        ),
        migrations.AlterField(
            model_name='tomcatwebapp',
            name='update_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='更新时间'),
        ),
    ]
