# Generated by Django 2.0.3 on 2018-06-25 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyeap_tomcat', '0002_auto_20180622_1329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tomcatserver',
            name='name',
        ),
        migrations.RemoveField(
            model_name='tomcatwebapp',
            name='name',
        ),
        migrations.AlterField(
            model_name='tomcatserver',
            name='alias',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Tomcat中文别名'),
        ),
        migrations.AlterField(
            model_name='tomcatserver',
            name='deploy_path',
            field=models.CharField(default='/local/server/', max_length=128, verbose_name='Tomcat部署路径'),
        ),
        migrations.AlterField(
            model_name='tomcatserver',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Tomcat服务编号'),
        ),
        migrations.AlterField(
            model_name='tomcatwebapp',
            name='alias',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='项目中文别名'),
        ),
        migrations.AlterField(
            model_name='tomcatwebapp',
            name='deploy_path',
            field=models.CharField(default='/local/webapp/', max_length=128, verbose_name='项目部署路径'),
        ),
    ]
