# Generated by Django 2.0.3 on 2018-06-10 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.BigAutoField(default=10000, primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=128)),
                ('student_age', models.IntegerField(blank=True, null=True)),
                ('student_sex', models.CharField(max_length=128)),
                ('student_card', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'student',
            },
        ),
    ]
