# Generated by Django 2.0.3 on 2018-06-10 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
