# Generated by Django 2.0.3 on 2018-06-10 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_auto_20180610_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.BigAutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
