# Generated by Django 2.0.3 on 2018-06-12 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0004_auto_20180610_1703'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('teacher_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('teacher_name', models.CharField(max_length=128)),
                ('teacher_sex', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'teacher',
            },
        ),
    ]
